---
codecov:
  notify:
    after_n_builds: 16
    wait_for_ci: true
coverage:
  status:
    project:
      # Mark project coverage info as informational only so that codecov stops complaining about it all the time
      default:
        informational: true
    patch:
      # Mark patch coverage info as informational only so that codecov stops complaining about it all the time
      default:
        informational: true
