---
default_language_version:
  python: python3
repos:
  # check some basic stuff
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Check Python source for debugger imports and
      # py37+ `breakpoint()`
      - id: debug-statements
  # Clean up imports in Python using isort
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--filter-files]
  # Format the python code with black
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  # Lint the yaml files
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
  # Lint the python code with flake
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  # Type check the Python code with MyPy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        pass_filenames: false
        types: [python]
        additional_dependencies: ['pyright@1.1.210']
