default_language_version:
    python: python3
repos:
# check some basic stuff
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    # Check for files that would conflict in case-insensitive filesystems
    - id: check-case-conflict
    # Check for files that contain merge conflict strings
    - id: check-merge-conflict
    # Check for debugger imports and py37+ `breakpoint()` calls in python source
    - id: debug-statements
# Clean up imports in Python using isort
-   repo: https://github.com/pycqa/isort
    rev: 5.3.2
    hooks:
    -   id: isort
        args: [--filter-files]
# Format the python code with black
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
# Lint the python code with flake
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3 
    hooks:
    - id: flake8
# Type check the Python code with MyPy
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.782'
    hooks:
    -   id: mypy

